"""phase5 questionnaire fields

Revision ID: 0e20b2694ed6
Revises: 74e73e656ddf
Create Date: 2026-10-02 11:56:50.228940
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '0e20b2694ed6'
down_revision: Union[str, Sequence[str], None] = '74e73e656ddf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questionnaire_questions', sa.Column('is_required', sa.Boolean(), server_default='true', nullable=False))
    op.add_column('questionnaire_questions', sa.Column('help_text', sa.Text(), nullable=True))
    op.add_column('questionnaire_questions', sa.Column('options_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('questionnaire_questions', 'options_json')
    op.drop_column('questionnaire_questions', 'help_text')
    op.drop_column('questionnaire_questions', 'is_required')
    # ### end Alembic commands ###
