"""phase9 photos storage moderation

Revision ID: 366eef283443
Revises: c924b54135f6
Create Date: 2026-10-02 12:42:29.580383
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '366eef283443'
down_revision: Union[str, Sequence[str], None] = 'c924b54135f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('photo_object_deletions',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('object_key', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=24), server_default='PENDING', nullable=False),
    sa.Column('attempts', sa.Integer(), server_default='0', nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('PENDING','DONE','FAILED')", name='ck_photo_object_deletions_status'),
    sa.CheckConstraint('attempts >= 0', name='ck_photo_object_deletions_attempts_nonnegative'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('object_key')
    )
    op.create_index('ix_photo_object_deletions_status', 'photo_object_deletions', ['status', 'created_at'], unique=False)
    op.create_table('photo_upload_tickets',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('object_key', sa.Text(), nullable=False),
    sa.Column('mime', sa.String(length=100), nullable=False),
    sa.Column('secret_hash', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=24), server_default='PREPARED', nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('consumed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('PREPARED','CONSUMED','CANCELLED','EXPIRED')", name='ck_photo_upload_tickets_status'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('object_key'),
    sa.UniqueConstraint('secret_hash')
    )
    op.create_index(op.f('ix_photo_upload_tickets_expires_at'), 'photo_upload_tickets', ['expires_at'], unique=False)
    op.create_index(op.f('ix_photo_upload_tickets_user_id'), 'photo_upload_tickets', ['user_id'], unique=False)
    op.create_index('ix_photo_upload_tickets_user_status', 'photo_upload_tickets', ['user_id', 'status'], unique=False)
    op.add_column('photos', sa.Column('byte_size', sa.BigInteger(), nullable=True))
    op.add_column('photos', sa.Column('object_etag', sa.String(length=160), nullable=True))
    op.add_column('photos', sa.Column('moderation_reason', sa.String(length=255), nullable=True))
    op.add_column('photos', sa.Column('moderated_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index('uq_photos_one_main_per_user', 'photos', ['user_id'], unique=True, postgresql_where=sa.text('is_main'))
    op.create_check_constraint(
        'ck_photos_moderation_status',
        'photos',
        "moderation_status IN ('PENDING','APPROVED','REJECTED')",
    )
    op.create_check_constraint(
        'ck_photos_positive_size',
        'photos',
        'byte_size IS NULL OR byte_size > 0',
    )
    op.create_check_constraint(
        'ck_photos_sort_order_nonnegative',
        'photos',
        'sort_order >= 0',
    )
    op.add_column('profiles', sa.Column('photos_completed', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('profiles', 'photos_completed')
    op.drop_constraint('ck_photos_sort_order_nonnegative', 'photos', type_='check')
    op.drop_constraint('ck_photos_positive_size', 'photos', type_='check')
    op.drop_constraint('ck_photos_moderation_status', 'photos', type_='check')
    op.drop_index('uq_photos_one_main_per_user', table_name='photos', postgresql_where=sa.text('is_main'))
    op.drop_column('photos', 'moderated_at')
    op.drop_column('photos', 'moderation_reason')
    op.drop_column('photos', 'object_etag')
    op.drop_column('photos', 'byte_size')
    op.drop_index('ix_photo_upload_tickets_user_status', table_name='photo_upload_tickets')
    op.drop_index(op.f('ix_photo_upload_tickets_user_id'), table_name='photo_upload_tickets')
    op.drop_index(op.f('ix_photo_upload_tickets_expires_at'), table_name='photo_upload_tickets')
    op.drop_table('photo_upload_tickets')
    op.drop_index('ix_photo_object_deletions_status', table_name='photo_object_deletions')
    op.drop_table('photo_object_deletions')
    # ### end Alembic commands ###
