"""phase4 profile markets

Revision ID: 74e73e656ddf
Revises: fc57398b3a81
Create Date: 2026-10-02 11:38:26.618142
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '74e73e656ddf'
down_revision: Union[str, Sequence[str], None] = 'fc57398b3a81'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('markets',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('country_code', sa.String(length=2), nullable=False),
    sa.Column('city_code', sa.String(length=32), nullable=False),
    sa.Column('display_name', sa.String(length=160), nullable=False),
    sa.Column('timezone', sa.String(length=80), nullable=False),
    sa.Column('currency_code', sa.String(length=3), nullable=False),
    sa.Column('default_language', sa.String(length=16), nullable=False),
    sa.Column('supported_languages', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('registration_open', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('matching_open', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    sa.UniqueConstraint('country_code', 'city_code', name='uq_markets_country_city')
    )
    op.create_index('ix_markets_active', 'markets', ['registration_open', 'matching_open'], unique=False)
    op.add_column('profiles', sa.Column('market_id', sa.BigInteger(), nullable=True))
    op.add_column('profiles', sa.Column('preferred_locale', sa.String(length=16), server_default='ru-KZ', nullable=False))
    op.drop_index(op.f('ix_profiles_matchable'), table_name='profiles')
    op.create_index('ix_profiles_matchable', 'profiles', ['eligibility_status', 'relationship_status', 'gender', 'seek_gender', 'market_id'], unique=False)
    op.create_index(op.f('ix_profiles_market_id'), 'profiles', ['market_id'], unique=False)
    op.create_foreign_key('fk_profiles_market_id', 'profiles', 'markets', ['market_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_profiles_market_id', 'profiles', type_='foreignkey')
    op.drop_index(op.f('ix_profiles_market_id'), table_name='profiles')
    op.drop_index('ix_profiles_matchable', table_name='profiles')
    op.create_index(op.f('ix_profiles_matchable'), 'profiles', ['eligibility_status', 'relationship_status', 'gender', 'seek_gender', 'city'], unique=False)
    op.drop_column('profiles', 'preferred_locale')
    op.drop_column('profiles', 'market_id')
    op.drop_index('ix_markets_active', table_name='markets')
    op.drop_table('markets')
    # ### end Alembic commands ###
