"""phase7 matching support

Revision ID: c924b54135f6
Revises: a9d4fe361bfe
Create Date: 2026-10-02 12:17:29.620426
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'c924b54135f6'
down_revision: Union[str, Sequence[str], None] = 'a9d4fe361bfe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('markets', sa.Column('latitude', sa.Numeric(precision=9, scale=6), nullable=True))
    op.add_column('markets', sa.Column('longitude', sa.Numeric(precision=9, scale=6), nullable=True))
    op.add_column('profiles', sa.Column('children_status', sa.String(length=40), server_default='', nullable=False))
    op.create_check_constraint(
        'ck_markets_latitude',
        'markets',
        'latitude IS NULL OR latitude BETWEEN -90 AND 90',
    )
    op.create_check_constraint(
        'ck_markets_longitude',
        'markets',
        'longitude IS NULL OR longitude BETWEEN -180 AND 180',
    )
    op.create_check_constraint(
        'ck_profiles_children_status',
        'profiles',
        "children_status IN ('','NO_CHILDREN','HAS_CHILDREN')",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('ck_profiles_children_status', 'profiles', type_='check')
    op.drop_constraint('ck_markets_longitude', 'markets', type_='check')
    op.drop_constraint('ck_markets_latitude', 'markets', type_='check')
    op.drop_column('profiles', 'children_status')
    op.drop_column('markets', 'longitude')
    op.drop_column('markets', 'latitude')
    # ### end Alembic commands ###
