"""phase7 matching support

Revision ID: c924b54135f6
Revises: a9d4fe361bfe
Create Date: 2026-10-02 12:17:29.620426
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'c924b54135f6'
down_revision: Union[str, Sequence[str], None] = 'a9d4fe361bfe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('markets', sa.Column('latitude', sa.Numeric(precision=9, scale=6), nullable=True))
    op.add_column('markets', sa.Column('longitude', sa.Numeric(precision=9, scale=6), nullable=True))
    op.add_column('profiles', sa.Column('children_status', sa.String(length=40), server_default='', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('profiles', 'children_status')
    op.drop_column('markets', 'longitude')
    op.drop_column('markets', 'latitude')
    # ### end Alembic commands ###
