"""initial postgres schema

Revision ID: de35f9d50310
Revises: 
Create Date: 2026-10-02 10:31:37.649716
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'de35f9d50310'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('actor_type', sa.String(length=40), nullable=False),
    sa.Column('actor_id', sa.String(length=160), nullable=True),
    sa.Column('action', sa.String(length=120), nullable=False),
    sa.Column('target_type', sa.String(length=80), nullable=True),
    sa.Column('target_id', sa.String(length=160), nullable=True),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('moderation_actions',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('actor', sa.String(length=160), nullable=False),
    sa.Column('target_type', sa.String(length=40), nullable=False),
    sa.Column('target_id', sa.String(length=80), nullable=False),
    sa.Column('action', sa.String(length=80), nullable=False),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('questionnaire_versions',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=160), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('settings',
    sa.Column('key', sa.String(length=120), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('referral_code', sa.String(length=64), nullable=False),
    sa.Column('referred_by', sa.BigInteger(), nullable=True),
    sa.Column('invites_sent', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('invites_sent >= 0', name='ck_users_invites_nonnegative'),
    sa.ForeignKeyConstraint(['referred_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('referral_code')
    )
    op.create_index('ix_users_email_lower', 'users', [sa.literal_column('lower(email)')], unique=True)
    op.create_table('blocks',
    sa.Column('blocker', sa.BigInteger(), nullable=False),
    sa.Column('blocked', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['blocked'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['blocker'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('blocker', 'blocked')
    )
    op.create_table('consents',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('consent_type', sa.String(length=100), nullable=False),
    sa.Column('version', sa.String(length=64), nullable=False),
    sa.Column('granted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_consents_user_id'), 'consents', ['user_id'], unique=False)
    op.create_table('data_requests',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('request_type', sa.String(length=40), nullable=False),
    sa.Column('status', sa.String(length=40), server_default='PENDING', nullable=False),
    sa.Column('requested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_data_requests_user_id'), 'data_requests', ['user_id'], unique=False)
    op.create_table('interests',
    sa.Column('from_user', sa.BigInteger(), nullable=False),
    sa.Column('to_user', sa.BigInteger(), nullable=False),
    sa.Column('state', sa.String(length=24), server_default='INTERESTED', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['from_user'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['to_user'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('from_user', 'to_user')
    )
    op.create_table('legacy_partner_criteria',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('raw_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('imported_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('marketing_attribution',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('utm_source', sa.String(length=255), server_default='', nullable=False),
    sa.Column('utm_medium', sa.String(length=255), server_default='', nullable=False),
    sa.Column('utm_campaign', sa.String(length=255), server_default='', nullable=False),
    sa.Column('utm_content', sa.String(length=255), server_default='', nullable=False),
    sa.Column('utm_term', sa.String(length=255), server_default='', nullable=False),
    sa.Column('referral_input', sa.String(length=255), server_default='', nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('matches',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user1', sa.BigInteger(), nullable=False),
    sa.Column('user2', sa.BigInteger(), nullable=False),
    sa.Column('compatibility_score', sa.Integer(), nullable=False),
    sa.Column('mutual_fit_score', sa.Integer(), nullable=False),
    sa.Column('algorithm_version', sa.String(length=64), server_default='legacy-v7', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('compatibility_score BETWEEN 0 AND 100', name='ck_matches_compatibility'),
    sa.CheckConstraint('mutual_fit_score BETWEEN 0 AND 100', name='ck_matches_mutual_fit'),
    sa.ForeignKeyConstraint(['user1'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user2'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user1', 'user2', name='uq_matches_pair')
    )
    op.create_index('ix_matches_user1_created', 'matches', ['user1', 'created_at'], unique=False)
    op.create_index('ix_matches_user2_created', 'matches', ['user2', 'created_at'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('kind', sa.String(length=80), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_table('partner_preferences',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('criterion_key', sa.String(length=80), nullable=False),
    sa.Column('importance', sa.String(length=20), server_default='IGNORE', nullable=False),
    sa.Column('value_text', sa.Text(), nullable=True),
    sa.Column('value_bool', sa.Boolean(), nullable=True),
    sa.Column('min_value', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('max_value', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('values_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("importance IN ('HARD','IMPORTANT','PREFERENCE','IGNORE')", name='ck_partner_preferences_importance'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'criterion_key', name='uq_partner_preferences_user_criterion')
    )
    op.create_index(op.f('ix_partner_preferences_user_id'), 'partner_preferences', ['user_id'], unique=False)
    op.create_table('photos',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('storage_key', sa.Text(), nullable=True),
    sa.Column('mime', sa.String(length=100), nullable=False),
    sa.Column('is_main', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('sort_order', sa.Integer(), server_default='0', nullable=False),
    sa.Column('moderation_status', sa.String(length=40), server_default='PENDING', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('storage_key')
    )
    op.create_index(op.f('ix_photos_user_id'), 'photos', ['user_id'], unique=False)
    op.create_index('ix_photos_user_status', 'photos', ['user_id', 'moderation_status'], unique=False)
    op.create_table('product_events',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_events_event_type'), 'product_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_product_events_user_id'), 'product_events', ['user_id'], unique=False)
    op.create_table('profiles',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('display_name', sa.String(length=120), server_default='', nullable=False),
    sa.Column('dob', sa.Date(), nullable=True),
    sa.Column('gender', sa.String(length=32), server_default='', nullable=False),
    sa.Column('seek_gender', sa.String(length=32), server_default='', nullable=False),
    sa.Column('city', sa.String(length=120), server_default='', nullable=False),
    sa.Column('country_code', sa.String(length=2), server_default='KZ', nullable=False),
    sa.Column('relationship_status', sa.String(length=40), server_default='PAUSED', nullable=False),
    sa.Column('eligibility_status', sa.String(length=40), server_default='NOT_ACTIVE_FOR_MATCHING', nullable=False),
    sa.Column('dating_goal', sa.String(length=80), server_default='', nullable=False),
    sa.Column('readiness_chat', sa.String(length=40), server_default='', nullable=False),
    sa.Column('readiness_offline', sa.String(length=40), server_default='', nullable=False),
    sa.Column('readiness_score', sa.Integer(), server_default='0', nullable=False),
    sa.Column('bio', sa.Text(), server_default='', nullable=False),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('smoking', sa.String(length=40), server_default='', nullable=False),
    sa.Column('alcohol', sa.String(length=40), server_default='', nullable=False),
    sa.Column('lifestyle', sa.String(length=80), server_default='', nullable=False),
    sa.Column('religion', sa.String(length=120), server_default='', nullable=False),
    sa.Column('nationality', sa.String(length=120), server_default='', nullable=False),
    sa.Column('children_attitude', sa.String(length=80), server_default='', nullable=False),
    sa.Column('children_plans', sa.String(length=80), server_default='', nullable=False),
    sa.Column('questionnaire_completed', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('profile_completed', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('status_confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('height IS NULL OR height BETWEEN 100 AND 250', name='ck_profiles_height'),
    sa.CheckConstraint('readiness_score BETWEEN 0 AND 100', name='ck_profiles_readiness_0_100'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index('ix_profiles_matchable', 'profiles', ['eligibility_status', 'relationship_status', 'gender', 'seek_gender', 'city'], unique=False)
    op.create_table('questionnaire_questions',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('version_id', sa.BigInteger(), nullable=False),
    sa.Column('legacy_qid', sa.Integer(), nullable=True),
    sa.Column('category', sa.String(length=120), nullable=False),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('answer_type', sa.String(length=40), server_default='scale', nullable=False),
    sa.Column('weight', sa.Numeric(precision=8, scale=4), server_default='1', nullable=False),
    sa.Column('match_logic', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['version_id'], ['questionnaire_versions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('version_id', 'legacy_qid', name='uq_questions_version_legacy_qid'),
    sa.UniqueConstraint('version_id', 'position', name='uq_questions_version_position')
    )
    op.create_table('sessions',
    sa.Column('token', sa.String(length=255), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('token')
    )
    op.create_index(op.f('ix_sessions_user_id'), 'sessions', ['user_id'], unique=False)
    op.create_table('user_status_history',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('relationship_status', sa.String(length=40), nullable=False),
    sa.Column('eligibility_status', sa.String(length=40), nullable=False),
    sa.Column('source', sa.String(length=40), server_default='migration', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_status_history_user_id'), 'user_status_history', ['user_id'], unique=False)
    op.create_table('conversations',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('match_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('match_id')
    )
    op.create_table('date_proposals',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('match_id', sa.BigInteger(), nullable=False),
    sa.Column('proposer', sa.BigInteger(), nullable=False),
    sa.Column('format', sa.String(length=80), nullable=False),
    sa.Column('when_text', sa.Text(), nullable=False),
    sa.Column('district', sa.String(length=160), server_default='', nullable=False),
    sa.Column('budget', sa.String(length=120), server_default='', nullable=False),
    sa.Column('note', sa.Text(), server_default='', nullable=False),
    sa.Column('status', sa.String(length=32), server_default='PENDING', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['proposer'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_date_proposals_match_id'), 'date_proposals', ['match_id'], unique=False)
    op.create_table('legacy_photo_blobs',
    sa.Column('photo_id', sa.BigInteger(), nullable=False),
    sa.Column('base64_data', sa.Text(), nullable=False),
    sa.Column('imported_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['photo_id'], ['photos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('photo_id')
    )
    op.create_table('match_score_components',
    sa.Column('match_id', sa.BigInteger(), nullable=False),
    sa.Column('component_key', sa.String(length=80), nullable=False),
    sa.Column('score', sa.Numeric(precision=8, scale=3), nullable=False),
    sa.Column('explanation_data', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('match_id', 'component_key')
    )
    op.create_table('questionnaire_answers',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('question_id', sa.BigInteger(), nullable=False),
    sa.Column('value_int', sa.Integer(), nullable=True),
    sa.Column('value_text', sa.Text(), nullable=True),
    sa.Column('value_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('answered_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['questionnaire_questions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'question_id')
    )
    op.create_table('messages',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('conversation_id', sa.BigInteger(), nullable=False),
    sa.Column('legacy_match_id', sa.BigInteger(), nullable=True),
    sa.Column('sender', sa.BigInteger(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sender'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_messages_conversation_id'), 'messages', ['conversation_id'], unique=False)
    op.create_table('reports',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('reporter', sa.BigInteger(), nullable=False),
    sa.Column('target_user', sa.BigInteger(), nullable=True),
    sa.Column('photo_id', sa.BigInteger(), nullable=True),
    sa.Column('message_id', sa.BigInteger(), nullable=True),
    sa.Column('reason', sa.String(length=160), nullable=False),
    sa.Column('status', sa.String(length=32), server_default='OPEN', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['photo_id'], ['photos.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['reporter'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_user'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reports_reporter'), 'reports', ['reporter'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reports_reporter'), table_name='reports')
    op.drop_table('reports')
    op.drop_index(op.f('ix_messages_conversation_id'), table_name='messages')
    op.drop_table('messages')
    op.drop_table('questionnaire_answers')
    op.drop_table('match_score_components')
    op.drop_table('legacy_photo_blobs')
    op.drop_index(op.f('ix_date_proposals_match_id'), table_name='date_proposals')
    op.drop_table('date_proposals')
    op.drop_table('conversations')
    op.drop_index(op.f('ix_user_status_history_user_id'), table_name='user_status_history')
    op.drop_table('user_status_history')
    op.drop_index(op.f('ix_sessions_user_id'), table_name='sessions')
    op.drop_table('sessions')
    op.drop_table('questionnaire_questions')
    op.drop_index('ix_profiles_matchable', table_name='profiles')
    op.drop_table('profiles')
    op.drop_index(op.f('ix_product_events_user_id'), table_name='product_events')
    op.drop_index(op.f('ix_product_events_event_type'), table_name='product_events')
    op.drop_table('product_events')
    op.drop_index('ix_photos_user_status', table_name='photos')
    op.drop_index(op.f('ix_photos_user_id'), table_name='photos')
    op.drop_table('photos')
    op.drop_index(op.f('ix_partner_preferences_user_id'), table_name='partner_preferences')
    op.drop_table('partner_preferences')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index('ix_matches_user2_created', table_name='matches')
    op.drop_index('ix_matches_user1_created', table_name='matches')
    op.drop_table('matches')
    op.drop_table('marketing_attribution')
    op.drop_table('legacy_partner_criteria')
    op.drop_table('interests')
    op.drop_index(op.f('ix_data_requests_user_id'), table_name='data_requests')
    op.drop_table('data_requests')
    op.drop_index(op.f('ix_consents_user_id'), table_name='consents')
    op.drop_table('consents')
    op.drop_table('blocks')
    op.drop_index('ix_users_email_lower', table_name='users')
    op.drop_table('users')
    op.drop_table('settings')
    op.drop_table('questionnaire_versions')
    op.drop_table('moderation_actions')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
