"""phase3 auth security

Revision ID: fc57398b3a81
Revises: de35f9d50310
Create Date: 2026-10-02 10:55:53.646448
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'fc57398b3a81'
down_revision: Union[str, Sequence[str], None] = 'de35f9d50310'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auth_outbox',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('channel', sa.String(length=20), nullable=False),
    sa.Column('recipient', sa.String(length=320), nullable=False),
    sa.Column('template', sa.String(length=80), nullable=False),
    sa.Column('payload_json', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('status', sa.String(length=24), server_default='PENDING', nullable=False),
    sa.Column('attempts', sa.Integer(), server_default='0', nullable=False),
    sa.Column('available_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_auth_outbox_pending', 'auth_outbox', ['status', 'available_at'], unique=False)
    op.create_table('auth_rate_limits',
    sa.Column('bucket_key', sa.String(length=128), nullable=False),
    sa.Column('window_started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('hits', sa.Integer(), server_default='0', nullable=False),
    sa.Column('blocked_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('hits >= 0', name='ck_auth_rate_limits_hits_nonnegative'),
    sa.PrimaryKeyConstraint('bucket_key')
    )
    op.create_table('auth_challenges',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('purpose', sa.String(length=40), nullable=False),
    sa.Column('channel', sa.String(length=20), nullable=False),
    sa.Column('target_hash', sa.String(length=64), nullable=False),
    sa.Column('secret_hash', sa.String(length=64), nullable=False),
    sa.Column('attempts', sa.Integer(), server_default='0', nullable=False),
    sa.Column('max_attempts', sa.Integer(), server_default='5', nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('consumed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('attempts >= 0', name='ck_auth_challenges_attempts_nonnegative'),
    sa.CheckConstraint('max_attempts BETWEEN 1 AND 20', name='ck_auth_challenges_max_attempts'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('secret_hash')
    )
    op.create_index(op.f('ix_auth_challenges_expires_at'), 'auth_challenges', ['expires_at'], unique=False)
    op.create_index(op.f('ix_auth_challenges_target_hash'), 'auth_challenges', ['target_hash'], unique=False)
    op.create_index(op.f('ix_auth_challenges_user_id'), 'auth_challenges', ['user_id'], unique=False)
    op.create_table('auth_identities',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('provider_subject', sa.String(length=255), nullable=False),
    sa.Column('provider_email', sa.String(length=320), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'provider_subject', name='uq_auth_identity_provider_subject')
    )
    op.create_index(op.f('ix_auth_identities_user_id'), 'auth_identities', ['user_id'], unique=False)
    op.add_column('sessions', sa.Column('secret_hash', sa.String(length=64), nullable=True))
    op.add_column('sessions', sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('sessions', sa.Column('user_agent_hash', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_sessions_secret_hash'), 'sessions', ['secret_hash'], unique=True)
    op.add_column('users', sa.Column('status', sa.String(length=32), server_default='ACTIVE', nullable=False))
    op.add_column('users', sa.Column('email_verified_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('phone_e164', sa.String(length=32), nullable=True))
    op.add_column('users', sa.Column('phone_verified_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('password_updated_at', sa.DateTime(timezone=True), nullable=True))
    op.create_unique_constraint('uq_users_phone_e164', 'users', ['phone_e164'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_users_phone_e164', 'users', type_='unique')
    op.drop_column('users', 'password_updated_at')
    op.drop_column('users', 'phone_verified_at')
    op.drop_column('users', 'phone_e164')
    op.drop_column('users', 'email_verified_at')
    op.drop_column('users', 'status')
    op.drop_index(op.f('ix_sessions_secret_hash'), table_name='sessions')
    op.drop_column('sessions', 'user_agent_hash')
    op.drop_column('sessions', 'last_seen_at')
    op.drop_column('sessions', 'secret_hash')
    op.drop_index(op.f('ix_auth_identities_user_id'), table_name='auth_identities')
    op.drop_table('auth_identities')
    op.drop_index(op.f('ix_auth_challenges_user_id'), table_name='auth_challenges')
    op.drop_index(op.f('ix_auth_challenges_target_hash'), table_name='auth_challenges')
    op.drop_index(op.f('ix_auth_challenges_expires_at'), table_name='auth_challenges')
    op.drop_table('auth_challenges')
    op.drop_table('auth_rate_limits')
    op.drop_index('ix_auth_outbox_pending', table_name='auth_outbox')
    op.drop_table('auth_outbox')
    # ### end Alembic commands ###
